<%@ Page Title="Depo |   Account Master" Language="VB" MasterPageFile="User.master" AutoEventWireup="false"
CodeFile="AccountMaster.aspx.vb" Inherits="Summary_BCYMovement" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
 
       
<head>
<title>Depo |Account Master</title>
       
</head>
<div class="page-container">
<div class="pageheader">
            
<h3>

<i class="glyphicon glyphicon-transfer"></i>  Account Master 
</h3>
           
</div>
       
<div id="page-content">
        
       
       
<asp:ScriptManager ID="ScriptManager1" runat="server">
</asp:ScriptManager>
<asp:UpdatePanel ID="UpdatePanel1" runat="server">
<ContentTemplate>
<div class="page-container" style="margin-left: -5px; margin-right: -5px; margin-top: -15px;">
<asp:Label ID="lblError" runat="server" Text="" ForeColor="red"></asp:Label>
<div class="col-md-3 pull-md-left sidebar" style="padding-top:12px;">
<div menuitemname="Client Details" class="panel panel-sidebar panel-sidebar">
<div class="panel-heading">
<h3 class="panel-title" style="padding-bottom: 0px !important; ">
<i class="fa fa-cube"></i>&nbsp; Account Master 
<%-- <i class="fa fa-chevron-up panel-minimise pull-right"></i>--%>
</h3>
</div>   
<div class="panel-body" Style="text-transform:lowercase;">
<asp:Repeater ID="rptnoLIst" runat="server">
<ItemTemplate>
<div  >
                             
                            
<a  href='<%# "AccountMaster.aspx?AccountIDView=" & Server.UrlEncode(Encrypt(DataBinder.Eval(Container.DataItem, "AccountID")).ToString())%>' target="_blank" ><strong><asp:Label runat="server"  Text='<%#Eval("AccountName")%>' ID="lblNONumber" style="text-transform:uppercase;"></asp:Label></strong></a>                                                     
<br /> <asp:Label runat="server" Text='<%#Eval("AddDate")%>' Id="lblDate" style="text-transform:uppercase;"></asp:Label>
<br/>Generated By: &nbsp;<asp:Label runat="server" Text='<%#Eval("Users")%>' Id="lbluser" style="text-transform:uppercase;"></asp:Label>
<br />
<asp:Label runat="server" >----------------------------------</asp:Label>
</div>
</ItemTemplate>
</asp:Repeater>
</div>
</div>
                           
</div>
<div class="panel-body">

<div class="row">
                                         
<div class="col-md-9 pull-md-right main-content" >
<fieldset class="register">
<div menuitemname="Client Details" class="panel panel-sidebar panel-sidebar">
<div class="panel-heading">
<h3 class="panel-title">
Account Master 
                
<%--<i class="fa fa-chevron-up panel-minimise pull-right"></i>--%>
</h3>
</div>
            
<div class="panel-body">
<asp:Panel ID="Panel2" runat="server" Enabled="true"> 

<div class="row">
<div class="col-sm-3 col-xs-12" >
<div class="form-group text-label" style="text-decoration-color:black">
<b >Account ID</b>
<asp:TextBox ID="txtAccountID" Style="text-transform: uppercase; background-color:#e9e9e9" ReadOnly  class="form-control text-label form-cascade-control"
runat="server" Text="" placeholder="NEW"></asp:TextBox>     
</div>
</div>

</div>

<div class="row">
<div class="col-md-6 col-xs-12">
<div class="form-group text-label">
<b  >Account Name</b>
<asp:TextBox ID="txtAccountName" Style="text-transform:uppercase" class="form-control text-label"  placeholder="Account Name"
runat="server"   ></asp:TextBox>
</div>
</div>
</div>

<div class="row">
<div class="col-md-6 col-xs-12">
<div class="form-group text-label">
<b  >Tally Name</b>
<asp:TextBox ID="txtTally" Style="text-transform:uppercase" class="form-control text-label"  placeholder="Tally Name"
runat="server"   ></asp:TextBox>
</div>
</div>
</div>

<div class="row" style="display:none">
<div class="col-md-5 col-xs-12">
<div class="form-group text-label">
<b  >Group Name</b>
<asp:DropDownList ID="ddlGroup" AutoPostBack="true" Style="text-transform: uppercase;" runat="server"  class="form-control text-label">
                                         
</asp:DropDownList> 
</div>
</div>
</div>

<div class="row">
<div class="col-md-2 col-xs-12">
<div class="form-group text-label">
<b  >Hsn Code</b>
<asp:TextBox ID="txtHsn" Style="text-transform:uppercase" class="form-control text-label" onkeypress="return ValidateQty()"  placeholder="Hsn Code"
runat="server"   ></asp:TextBox>
</div>
</div>
          <div class="col-md-4 col-xs-12">
<div class="form-group text-label">
<b  >HSN Charges Description</b>
<asp:TextBox ID="txtChargesDescription" Style="text-transform:uppercase" class="form-control text-label"   placeholder="Charges Description"
runat="server"   ></asp:TextBox>
</div>
</div>                       
</div>

    <div class="row">

                                 
</div>
 
<div class="row">
<div class="col-md-3 col-xs-12">
<div class="form-group text-label">
<b  >Display Priority</b>
<asp:TextBox runat="server" ID="txtDisplay" CssClass="form-control" placeholder="Display Priority"></asp:TextBox>
</div>
</div>

<div class="col-md-6 col-xs-12">
<div class="form-group text-label" style="padding-top:22px;">
<asp:CheckBox ID="chkisActive" runat="server" Checked="true" />
<asp:hiddenfield ID="Hiddenfield1" runat="server" Value="0" />
<asp:Label ID="Label1" runat="server" AssociatedControlID="chkisActive" CssClass="inline"> Is Active?</asp:Label>
</div>
</div>

                                 
</div>
 
                               
</asp:Panel>
                        
</div>
</div>


<div class="row">
<div class="col-sm-1">
<div class="form-group" style="padding-top:15px">
<asp:Button ID="btnSave" class="btn btn-primary btn btn-sm outline " runat="server" OnClick="btnSave_Click"  
Text="Save"  OnClientClick="return ValidationSave()" />
</div>
                                              
                                      
</div>
                       
<div class="col-sm-1" style="padding-left:14px;">
<div class="form-group" style="padding-top:15px">
                           
<a href="AccountMaster.aspx" id="btnclear" runat="server" class="btn btn-primary ">
Clear
</a> 
                              
</div>
                                              
                                      
</div>
<div class="col-sm-5 pull-right" style="padding-top:25px;">
<div class="form-group">
<a href="AccountSummary.aspx" target="_blank"><b style="color:blue">Click here to views list of accounts head</b> </a>
</div>
</div>
                         
</div>
<asp:Label ID="lblAccountID" Visible="false" runat="server" Text=""></asp:Label>
<asp:Label ID="lblAccountName" Visible="false" runat="server" Text=""></asp:Label>
<asp:Label ID="lblagentname" Visible="false" runat="server" Text=""></asp:Label>
             
                      
                    
                   
                         
<div class="modal fade control-label" id="myModalforupdate" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-dialog modal-sm">
<asp:UpdatePanel ID="UpdatePanel3" runat="server" ChildrenAsTriggers="false" UpdateMode="Conditional">
<ContentTemplate>
<div class="modal-content">
<div class="modal-header">
<center>
<span><i runat="server" id="I3" class="fa fa-5x fa-check-circle-o text-success"></i></span>
<br />
<h4 class="modal-title">

<asp:Label ID="lblSession" CssClass="control-label" Font-Bold="true" runat="server" Text=""></asp:Label></h4>
</center>
</div>
<div class="modal-footer">
                   
<a href="AccountMaster.aspx" class="btn btn-info btn-block">OK</a>
                                
</div>
</div>
                    
</ContentTemplate>
             
</asp:UpdatePanel>
</div>
</div>
               
</fieldset>

</div>
</div>
                               
</div>
                           
                          
                     
                       
                       
</div>
                 
</ContentTemplate>
</asp:UpdatePanel>
</div>
       
         
</div>
   
<script type="text/javascript">
function ValidationSave() {
                 
var txtAccountName = document.getElementById('<%= txtAccountName.ClientID%>').value;
                   
               

var blResult = Boolean;
blResult = true;
 

                   
if (txtAccountName == "") {
document.getElementById('<%= txtAccountName.ClientID%>').style.borderColor = "red";
blResult = blResult && false;

}
 
//alert('hi')
if (blResult == false) {
alert('Please fill the required fields!');
}
return blResult;
}
</script>

<script type="text/javascript">
function ValidateQty() {
//alert('hii')
if ((event.keyCode > 47 && event.keyCode < 58) || event.keyCode == 46)
return event.returnValue;
return event.returnValue = '';
}

function checkEmail(str) {
var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;

if (reg.test(emailField.value) == false) {
alert('Invalid Email Address');
return false;
}

return true;
}

function CheckTelephone(tel) {

if (tel.length < 7)
alert("Invalid Telephone number.")
}

function CheckMobile(mob) {
if (mob.length < 10)
alert("Invalid Mobile number.");

}
</script>
</asp:Content>
