<%@ Page Title="Depo |   Party Gst Master" Language="VB" MasterPageFile="User.master" AutoEventWireup="false"
CodeFile="PartyGstMaster.aspx.vb" Inherits="Summary_BCYMovement" Culture="en-GB" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
 
       
<head>
<title>ColdStorage |    Party Gst Master</title>
       
</head>
<div class="page-container">
<div class="pageheader">
            
<h3>

<i class="glyphicon glyphicon-transfer"></i>  Party Gst Master 
</h3>
           
</div>
       
<div id="page-content">
        
       
       
<asp:ScriptManager ID="ScriptManager1" runat="server">
</asp:ScriptManager>
            
<div class="page-container" style="margin-left: -5px; margin-right: -5px; margin-top: -15px;">
<asp:Label ID="lblError" runat="server" Text="" ForeColor="red"></asp:Label>
<div class="col-md-3 pull-md-left sidebar" style="padding-top:12px;">
<div menuitemname="Client Details" class="panel panel-sidebar panel-sidebar">
<div class="panel-heading">
<h3 class="panel-title" style="padding-bottom: 0px !important; ">
<i class="fa fa-cube"></i>&nbsp; Party Gst Master 
<%-- <i class="fa fa-chevron-up panel-minimise pull-right"></i>--%>
</h3>
</div>   
<div class="panel-body" Style="text-transform:lowercase;">
<asp:Repeater ID="rptnoLIst" runat="server">
<ItemTemplate>
<div  >
                             
                            
<a  href='<%# "PartyGSTMaster.aspx?GSTIDView=" & Server.UrlEncode(Encrypt(DataBinder.Eval(Container.DataItem, "GSTID")).ToString())%>' target="_blank" ><strong><asp:Label runat="server"  Text='<%#Eval("GSTName")%>' ID="lblNONumber" style="text-transform:uppercase;"></asp:Label></strong></a>                                                     
<br /> <asp:Label runat="server" Text='<%#Eval("AddDate")%>' Id="lblDate" style="text-transform:uppercase;"></asp:Label>
<br/>Generated By: &nbsp;<asp:Label runat="server" Text='<%#Eval("Users")%>' Id="lbluser" style="text-transform:uppercase;"></asp:Label>
<br />
<asp:Label runat="server" >----------------------------------</asp:Label>
</div>
</ItemTemplate>
</asp:Repeater>
</div>
</div>
                           
</div>
<div class="panel-body">

<div class="row">
                                         
<div class="col-md-9 pull-md-right main-content" >
<fieldset class="register">
<div menuitemname="Client Details" class="panel panel-sidebar panel-sidebar">
<div class="panel-heading">
<h3 class="panel-title">
Party Gst Master 
                
<%--<i class="fa fa-chevron-up panel-minimise pull-right"></i>--%>
</h3>
</div>
            
<div class="panel-body">
<asp:Panel ID="Panel2" runat="server" Enabled="true"> 

<div class="row">
<div class="col-sm-2  col-xs-12" >
<div class="form-group text-label" style="text-decoration-color:black">
<b >ID</b>
<asp:TextBox ID="txtID" Style="text-transform: uppercase; background-color:#e9e9e9" ReadOnly  class="form-control text-label form-cascade-control"
runat="server" Text="" placeholder="NEW"></asp:TextBox>     
</div>
</div>

</div>
<div class="row">

                  
<div class="col-md-3 col-xs-12">
<div class="form-group text-label">
<b  >Type Of Registration</b>
<asp:DropDownList ID="ddltypeof"  Style="text-transform:  uppercase;" AutoPostBack="true" OnSelectedIndexChanged="ddltypeof_SelectedIndexChanged" runat="server"  class="form-control text-label">    
<asp:ListItem Value="Registered">Registered</asp:ListItem> 
<asp:ListItem Value="UnRegistered">UnRegistered</asp:ListItem>                                   
</asp:DropDownList> 
</div>
</div>
</ContentTemplate>
</asp:UpdatePanel>
                             
<div class="col-md-3  col-xs-12" ">                                      
<div class="form-group text-label">
<b >Date Of Possession</b>
<asp:TextBox ID="txtdate"  placeholder="dd-mm-yyyy " TextMode="Date"  runat="server"   BackColor="White" Class="form-control text-label"></asp:TextBox>

</div>                        
</div>

                              
</div>
<asp:UpdatePanel ID="UpdatePanel4" runat="server" UpdateMode="Conditional">
<ContentTemplate>
<div class="row">
<div class="col-md-6 col-xs-12">
<div class="form-group text-label">
<b  >Gst In/Unique ID</b>
<asp:TextBox ID="txtGstUniqu" Style="text-transform:uppercase" AutoPostBack="true" OnTextChanged="txtUniqueid_TextChanged" class="form-control text-label"  placeholder="Gst In/Unique ID"
runat="server"  MaxLength="15"  ></asp:TextBox>
</div>
</div>
</div>
                              
                               
<div class="row">
<div class="col-md-6 col-xs-12">
<div class="form-group text-label">
<b  >Pan No</b>
<asp:TextBox ID="txtpanno" Style="text-transform:uppercase" class="form-control text-label"  placeholder="Pan No"
runat="server"   ></asp:TextBox>
</div>
</div>
                                 
</div>
<div class="row">
<div class="col-md-12 col-xs-12">
<div class="form-group text-label">
<b  >Name</b>
<asp:TextBox ID="txtname" Style="text-transform:uppercase" class="form-control text-label"    placeholder="Name"
runat="server"   ></asp:TextBox>
</div>
</div>
                                 
</div>

<div class="row">
<div class="col-md-12 col-xs-12">
<div class="form-group text-label">
<b  >Address</b>
<asp:TextBox ID="txtAddress" Style="text-transform:uppercase" class="form-control text-label"    placeholder="Address"
runat="server" TextMode="MultiLine" Rows="2"></asp:TextBox>
</div>
</div>
                                 
</div>
                           
<div class="row">
<asp:Panel ID="Panel3" runat="server" Enabled="true"> 
<div class="col-md-6 col-xs-12">
<div class="form-group text-label">
<b  >State </b>
<asp:DropDownList ID="ddlState"   Style="text-transform: uppercase;" runat="server"    class="form-control text-label">
<asp:ListItem Value="0">--Select--</asp:ListItem>      
</asp:DropDownList> 
</div>
</div>
                           
<div class="col-md-3 col-xs-12">
<div class="form-group text-label">
<b  >State code</b>
<asp:TextBox ID="txtstateco" Style="text-transform:uppercase" class="form-control text-label"  placeholder="State code"
runat="server"   ></asp:TextBox>
</div>
</div>
  
</asp:Panel>

      <div class="col-md-3 col-xs-12">
<div class="form-group text-label">
<b  >Pin code</b>
<asp:TextBox ID="txtPincode" Style="text-transform:uppercase" class="form-control text-label"  placeholder="Pin code"
runat="server"   ></asp:TextBox>
</div>
</div>
</div>

<div class="row">
<div class="col-md-6 col-xs-12">
<div class="form-group text-label">
<b>Party Type </b>
<asp:DropDownList ID="ddlParty" AutoPostBack="true" OnSelectedIndexChanged="ddlParty_SelectedIndexChanged" Style="text-transform: uppercase;" runat="server"  class="form-control text-label">
<asp:ListItem Value="Customer">Customer</asp:ListItem> 
<asp:ListItem Value="NA">NA</asp:ListItem> 
</asp:DropDownList> 
</div>
</div>
<asp:Panel ID="Panel1" runat="server" Enabled="true"> 
<div class="col-md-6 col-xs-12" style="display:none;" id="divName" runat="server">
<div class="form-group text-label">
<b  >Name </b>
<asp:DropDownList ID="ddlname" AutoPostBack="true" Style="text-transform: uppercase;" runat="server"  class="form-control text-label">
                                              
</asp:DropDownList> 
</div>
</div>
</asp:Panel>
</div>

<div class="row">
<div class="col-md-6 col-xs-12">
<div class="form-group text-label">
<b  >Email ID</b>
<asp:TextBox ID="txtEmail" Style="text-transform:uppercase" class="form-control text-label"    placeholder="Email ID"
runat="server"   ></asp:TextBox>
</div>
</div>
                                 
<div class="col-md-6 col-xs-12">
<div class="form-group text-label">
<b  >Contact No</b>
<asp:TextBox ID="txtcontact" Style="text-transform:uppercase" class="form-control text-label" onkeypress="return ValidatePhoneNo()"  placeholder="999 999 9999" MaxLength="10"
runat="server"   ></asp:TextBox>
</div>
</div>
                                 
</div>



                            
                        

</ContentTemplate>
</asp:UpdatePanel>
    <div class="row">
<div class="col-sm-1">
<div class="form-group" style="padding-top:15px">
<asp:Button ID="btnSave" class="btn btn-primary  btn-sm outline" runat="server" OnClick="btnSave_Click"
Text="Save"  OnClientClick="return ValidationSave()" />
</div>
                                              
                                      
</div>
                       
<div class="col-sm-1" style="padding-left:14px;">
<div class="form-group" style="padding-top:15px">
                           
<a href="PartyGSTMaster.aspx" id="btnclear" runat="server" class="btn btn-primary btn-sm outline ">
Clear
</a> 
                              
</div>
                                              
                                      
</div>
<div class="col-sm-5 pull-right" style="padding-top:25px;">
<div class="form-group">
<a href="PartyGSTSummary.aspx" target="_blank"><b style="color:blue">Click here to view Party GST summary</b> </a>
</div>
</div>
                         
</div>
</asp:Panel>
</div>
    </div>

 <asp:Panel ID="Panel4" runat="server" Enabled="true">
 <div menuitemname="Client Details" class="panel panel-sidebar panel-sidebar">
     <div class="panel-body">
     <div class="col-md-6 col-xs-12">
<div class="form-group text-label">
<b  >Search</b>
<asp:TextBox ID="txtSearch" Style="text-transform:uppercase" class="form-control text-label"  placeholder="Search"
runat="server"   ></asp:TextBox>
</div>
</div>

         <div class="col-sm-1">
<div class="form-group" style="padding-top:20px">
<asp:Button ID="btnSearch" class="btn btn-primary  btn-sm outline" runat="server"
Text="Search" />
</div>
                                              
                                      
</div>
  
         
      <div class="row">
<div class="col-lg-12 col-xs-12 text-label ">
<div class="table-responsive">
<asp:GridView ID="GrdGSTPartySearch" runat="server" ForeColor="Black" CssClass="table table-striped table-bordered table-hover scrolling-table-container"
AutoGenerateColumns="False" EmptyDataText="No records found!" ShowHeaderWhenEmpty="true"   AllowPaging="true" PageSize="10" >
<pagerstyle backcolor="white" ForeColor="blue" Font-Underline="false" height="30px" verticalalign="Bottom" horizontalalign="center"/> 
<Columns>
 
   <asp:TemplateField>
<ItemTemplate>
                                                          
<a  href='<%# "PartyGSTMaster.aspx?GSTIDEdit=" & Server.UrlEncode(Encrypt(DataBinder.Eval(Container.DataItem, "GSTID")).ToString())%>'
Class='btn btn-info btn-xs outline' 
>Edit</a>
                                                         
</ItemTemplate>
<ItemStyle HorizontalAlign="Left" Width="60px" />
</asp:TemplateField>
    
                                                    
<asp:BoundField DataField="GSTID" HeaderText="GSTID" HeaderStyle-CssClass="header-center" ItemStyle-HorizontalAlign="right"></asp:BoundField>
<asp:BoundField DataField="GSTName" HeaderText="GSTName" HeaderStyle-CssClass="header-center" ItemStyle-HorizontalAlign="left"></asp:BoundField>
    <asp:BoundField DataField="GSTAddress" HeaderText="GSTAddress" HeaderStyle-CssClass="header-center" ItemStyle-HorizontalAlign="left"></asp:BoundField>
<asp:BoundField DataField="State" HeaderText="State" HeaderStyle-CssClass="header-center" ItemStyle-HorizontalAlign="left"></asp:BoundField>
         

                                             
     
</Columns>

</asp:GridView>
</div>
</div>
</div>
         
               

</div>
   </div>
         </asp:Panel>


</div>
<asp:Label ID="lblID" Visible="false" runat="server" Text=""></asp:Label>
<asp:Label ID="lblcode" Visible="false" runat="server" Text=""></asp:Label>
<asp:Label ID="lblagentname" Visible="false" runat="server" Text=""></asp:Label>
             
                      
                    
                               
                   
                         
<div class="modal fade control-label" id="myModalforupdate" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-dialog modal-sm">
<asp:UpdatePanel ID="UpdatePanel3" runat="server" ChildrenAsTriggers="false" UpdateMode="Conditional">
<ContentTemplate>
<div class="modal-content">
<div class="modal-header">
<center>
<span><i runat="server" id="I3" class="fa fa-5x fa-check-circle-o text-success"></i></span>
<br />
<h4 class="modal-title">

<asp:Label ID="lblSession" CssClass="control-label" Font-Bold="true" runat="server" Text=""></asp:Label></h4>
</center>
</div>
<div class="modal-footer">
                   
<a href="PartyGSTMaster.aspx" class="btn btn-info btn-block">OK</a>
                                
</div>
</div>
                    
</ContentTemplate>
             
</asp:UpdatePanel>
</div>
</div>

<div class="modal fade control-label" id="myModalforupdate1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-dialog modal-sm">
<asp:UpdatePanel ID="UpdatePanel2" runat="server" ChildrenAsTriggers="false" UpdateMode="Conditional">
<ContentTemplate>
<div class="modal-content">
<div class="modal-header">
<center>
<span><i runat="server" id="I1" class="fa fa-5x fa-check-circle-o text-success"></i></span>
<br />
<h4 class="modal-title">

<asp:Label ID="lblSession1" CssClass="control-label" Font-Bold="true" runat="server" Text=""></asp:Label></h4>
</center>
</div>
<div class="modal-footer">
<button id="btnok1" class="btn btn-info" runat="server" data-dismiss="modal" onserverclick="btnok1_ServerClick" aria-hidden="true">Yes</button>
<button class="btn btn-info" runat="server" data-dismiss="modal" aria-hidden="true">No</button>
                                
</div>
</div>
                    
</ContentTemplate>
             
</asp:UpdatePanel>
</div>
</div>
               
</fieldset>

</div>
</div>
                               
</div>
                           
                          
                     
                       
                       
</div>
                 
                
</div>
       
         
 s
   
<script type="text/javascript">
function ValidationSave()
{

var ddltypeof = document.getElementById('<%= ddltypeof.ClientID%>').value;
var txtGstUniqu = document.getElementById('<%= txtGstUniqu.ClientID%>').value;
var txtpanno = document.getElementById('<%= txtpanno.ClientID%>').value;
var txtname = document.getElementById('<%= txtname.ClientID%>').value;
var txtstateco = document.getElementById('<%= txtstateco.ClientID%>').value;
var txtAddress = document.getElementById('<%= txtAddress.ClientID%>').value;
var txtcontact = document.getElementById('<%=txtcontact.ClientID%>').value;
var txtEmail = document.getElementById('<%=txtEmail.ClientID%>').value;
var ddlState = document.getElementById('<%=ddlState.ClientID%>').value;
var ddlParty = document.getElementById('<%=ddlParty.ClientID%>').value;
                
                 

var blResult = Boolean;
blResult = true;
                 
                  
 
//alert('hi')
if (txtGstUniqu == "") {
document.getElementById('<%= txtGstUniqu.ClientID%>').style.borderColor = "red";
blResult = blResult && false;

}

                   
if (txtpanno == "") {
document.getElementById('<%= txtpanno.ClientID%>').style.borderColor = "red";
blResult = blResult && false;

}

                   
if (txtname == "") {
document.getElementById('<%= txtname.ClientID%>').style.borderColor = "red";
blResult = blResult && false;

}

                   
if (txtstateco == "") {
document.getElementById('<%= txtstateco.ClientID%>').style.borderColor = "red";
blResult = blResult && false;

}
                    
if (txtAddress == "") {
document.getElementById('<%= txtAddress.ClientID%>').style.borderColor = "red";
blResult = blResult && false;

}
 
                  

                
if (blResult == false) {
alert('Please fill the required fields!');
}
return blResult;
}
</script>

<script type="text/javascript">
function ValidateQty() {
//alert('hii')
if ((event.keyCode > 47 && event.keyCode < 58) || event.keyCode == 46)
return event.returnValue;
return event.returnValue = '';
}

function checkEmail(str) {
var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;

if (reg.test(emailField.value) == false) {
alert('Invalid Email Address');
return false;
}

return true;
}

function CheckTelephone(tel) {

if (tel.length < 7)
alert("Invalid Telephone number.")
}

function CheckMobile(mob) {
if (mob.length < 10)
alert("Invalid Mobile number.");

}
</script>

<script type="text/javascript">
function ValidatePhoneNo() {
//alert('hii')
if ((event.keyCode > 47 && event.keyCode < 58) || event.keyCode == 43 || event.keyCode == 32 || event.keyCode == 40 || event.keyCode == 41)
return event.returnValue;
return event.returnValue = '';
}

function checkEmail(str) {
var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;

if (reg.test(emailField.value) == false) {
alert('Invalid Email Address');
return false;
}

return true;
}

function CheckTelephone(tel) {

if (tel.length < 7)
alert("Invalid Telephone number.")
}

function CheckMobile(mob) {
if (mob.length < 10)
alert("Invalid Mobile number.");

}
</script>
</asp:Content>
